# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

# Set working directory
WORKDIR /app

# Copy package files
COPY package.json pnpm-lock.yaml ./

# Install pnpm (if not pre-installed)
RUN npm install -g pnpm

# Install dependencies (skip install scripts, then build)
RUN pnpm install --ignore-scripts

# Copy source files
COPY . .

# Build the project
RUN pnpm run build

# Expose port if necessary (MCP likely communicates over stdio, so not needed)

# Set the entrypoint
CMD [ "node", "dist/cli.js" ]
